name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  ci:
    # Name the Job
    name: Continuous Integration of Codebase
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Installs dependencies
      - name: Install Dependencies
        run: npm ci

      - name: Install Peer Dependencies
        run: npx install-peerdeps --dev eslint-config-wesbos

      - name: Install Frontend Dependencies
        run: cd frontend && npm ci

      - name: Install Backend Dependencies
        run: cd backend && npm ci

      # Runs the Super-Linter action
      - name: Linting
        run: npm run lint
